name: flutter_realtime_workspace
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  # --- AUTHENTICATION ---
  firebase_auth: ^5.2.0
  google_sign_in: ^6.2.1
  github_sign_in_plus: ^0.0.2
  msal_auth: ^3.1.4
  pin_code_fields: ^8.0.1
  # flutter_facebook_auth: ^6.0.4

  # --- STORAGE ---
  firebase_core: ^3.4.0
  firebase_storage: ^12.3.1
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.4
  cloud_firestore: ^5.6.8
  firebase_messaging: ^15.2.6
  get_storage: ^2.1.1
  flutter_dotenv: ^5.2.1

  # --- FILES / MEDIA ---
  image_picker: ^1.1.2

  # --- UTILITIES ---
  http: ^0.13.5
  dio: ^5.8.0+1
  intl: ^0.20.2
  logger: ^2.4.0
  url_launcher: ^6.3.0
  pull_to_refresh: ^2.0.0
  # flutter_vibrate: ^1.3.0
  connectivity_plus: ^6.0.5
  status_alert: ^1.0.1
  table_calendar: ^3.2.0
  flutter_animated_icons: ^1.0.1
  form_validator: ^2.1.1
  smooth_page_indicator: ^1.2.0+3
  google_maps_flutter: ^2.9.0
  geolocator: ^13.0.1
  percent_indicator: ^4.2.5
  local_auth: ^2.3.0
  uuid: ^4.5.0
  wakelock_plus: ^1.3.2

  # --- UI / ICONS ---
  sign_button: ^2.0.6
  flutter_neumorphic_plus: ^3.4.0
  carousel_slider: ^5.0.0
  syncfusion_flutter_charts: ^29.2.5
  fl_chart: ^1.0.0
  gantt_chart: ^0.3.0
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  # --- STATE MANAGEMENT ---
  flutter_riverpod: ^2.5.1
  get: ^4.6.6
  socket_io_client: ^3.1.2

  # --- PRODUCT SPECIFIC PACKAGES ---
  # Add any product-specific packages here

  # --- TOASTS / ALERTS ---
  fluttertoast: ^8.2.12
  flutter_spinkit: ^5.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# flutter_slidable:
#     git:
#       url: https://github.com/letsar/flutter_slidable.git
#       ref: master

dependency_overrides: 
  flare_flutter : ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/logo/
    # - assets/icons/
    - assets/images/
    - assets/lotties/projectGIF.gif
    - assets/
   
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.otf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.otf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.otf
          style: italic
        - asset: assets/fonts/Poppins-Medium.otf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.otf
          weight: 800


