// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo9uPfR-ly7j4agMMBE0Z9mSL7PsnrF8o',
    appId: '1:869338390823:web:c27b6283124623b7244902',
    messagingSenderId: '869338390823',
    projectId: 'flutter-realtime-workspace',
    authDomain: 'flutter-realtime-workspace.firebaseapp.com',
    storageBucket: 'flutter-realtime-workspace.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqWuVkYZt5RVyNOggzI-s1E9w7HJ7oheE',
    appId: '1:869338390823:android:4bcfe3e94225b7a4244902',
    messagingSenderId: '869338390823',
    projectId: 'flutter-realtime-workspace',
    storageBucket: 'flutter-realtime-workspace.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfGj7bcIw9g57__UIchGtQzWNAUwRT3WA',
    appId: '1:869338390823:ios:069184f7338d8128244902',
    messagingSenderId: '869338390823',
    projectId: 'flutter-realtime-workspace',
    storageBucket: 'flutter-realtime-workspace.appspot.com',
    iosBundleId: 'com.example.flutterRealtimeWorkspace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfGj7bcIw9g57__UIchGtQzWNAUwRT3WA',
    appId: '1:869338390823:ios:069184f7338d8128244902',
    messagingSenderId: '869338390823',
    projectId: 'flutter-realtime-workspace',
    storageBucket: 'flutter-realtime-workspace.appspot.com',
    iosBundleId: 'com.example.flutterRealtimeWorkspace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDo9uPfR-ly7j4agMMBE0Z9mSL7PsnrF8o',
    appId: '1:869338390823:web:40d805e2d0b6ae69244902',
    messagingSenderId: '869338390823',
    projectId: 'flutter-realtime-workspace',
    authDomain: 'flutter-realtime-workspace.firebaseapp.com',
    storageBucket: 'flutter-realtime-workspace.appspot.com',
  );
}
